### ISSUE TITLE
Timezone parameter

### ISSUE THREAD

**Issue by cristipp** [borgar/numfmt#6]
Great library, thanks for the hard work. Reading the code indicates that the timezone is hardcoded to the browser timezone, see https://github.com/borgar/numfmt/blob/master/lib/numformat.js#L46. Would there be a chance to add a timezone parameter, just like there is a locale parameter?

Thank you.

**Comment by borgar** [comment]
This library is trying to not have much concept of timezones since it is designed for Spreadsheet software, which is agnostic to them. That line of code you refer to is essentially there to maintain some compatibility with SSF which [has this same behaviour](https://github.com/SheetJS/ssf/blob/e71eeda4d2a8fb23ba8782dfa7f3688d8e19aa5e/bits/35_datecode.js#L39).

As you can see by PR #5 I am currently working on adding more options to the library and reconsidering some backwards compatibility choices in favor of more usability. So I am very open to changing this and/or adding an option.

The question is what behaviour and/or options would be most useful here?

----

Firstly, the input. I think that the best way to set this up is to move date conversion into a separate function:

```js
const jsDate = new Date(...);
const serialDate = numfmt.dateToSerial(jsDate, { localtime: true });
numfmt.format("hh:mm \E\D\T", serialDate); // "11:43 EDT"
```

And then use that same function internally when argument is a date:

```js
const myDate = new Date(...);
numfmt.format("hh:mm \E\D\T", myDate, { localtime: true }); // "11:43 EDT"
```

That way the conversion is contained and can be tested (and used) separately. What would be useful for this function to be able to do (in terms of configuration)?

----

Secondly, the output. There is nothing in the specification to emit timezone information. I'm a little wary of extending the spec by taking over an unused character as someone may rely on the side-effect of un-semantic characters generally being allowed to pass through. There are some options however:

* Use a combination of more than 1 character (like `TZ`):

  ```js
  numfmt.format('hh:mm tz', date, { timezone: 'EDT' }); // '11:43 EDT'
  ```

* Only allow taking over a character (like `Z`) when a timezone setting is used:

  ```js
  numfmt.format('hh:mm z', date, { timezone: 'EDT' }); // '11:43 EDT'
  numfmt.format('hh:mm z', date); // '11:43 z'
  ```

* User must provide the zone identifier as string as a part of the format:

  ```js
  numfmt.format('hh:mm \E\D\T', date); // "11:43 EDT"
  numfmt.format('hh:mm "EDT"', date); // "11:43 EDT"
  ```

  Since the formatter itself will always end up working with a normalized date and timezone is essentially just an identifier being passed through to the output, this seems just as viable? 🤷‍♂️ 

---

Full disclaimer: I currently make my living writing Spreadsheet based software and I live in a non-DST GMT timezone. So I don't have particularly strong opinion on what is most useful here. 🙂

**Comment by cristipp** [comment]
Some thoughts: A timezone-agnostic library is great. Right now neither SSF nor numfmt nor Date.toString are so, because they use the browser timezone when formatting:

```
expect(numfmt.format('yyyy-mm-dd hh:mm:ss', new Date('2020-10-20'))).toEqual('2020-10-19 17:00:00');
expect(new Date('2020-10-20').toString()).toEqual('Mon Oct 19 2020 17:00:00 GMT-0700 (Pacific Daylight Time)');
expect(new Date('2020-10-20').toLocaleString()).toEqual('10/19/2020, 5:00:00 PM');
expect(new Date('2020-10-20').toUTCString()).toEqual('Tue, 20 Oct 2020 00:00:00 GMT');
expect(new Date('2020-10-20').toISOString()).toEqual('2020-10-20T00:00:00.000Z');
```

OTOH, the ECMA-376 spec is timezone agnostic. I'd be weary of extending the spec in any way. I'm merely going to wave towards Unicode TR 35, which is used by https://date-fns.org/v2.19.0/docs/format, but which is also widely out of scope for the numfmt library.

On further digging:
* Google sheets uses ''elapsed days since the epoch of 30 December 1899 00:00:00 UTC", see https://googlesheets4.tidyverse.org/articles/articles/dates-and-times.html
* Excel uses "date/time is in terms of the local time on the computer", https://stackoverflow.com/a/46013271

Given that, perhaps just having the option to switch between the two interpretation modes ```numfmt.format(`yyyy-mm-dd hh:mm:ss`, date, { timemode: 'utc' | 'local' });``` would suffice.

I ended up using `parseAsLocalDate`, with the property that `format(parse(x)) === x`. There are likely hidden dragons this path, but will have to do for now.

```
const tzoffset = new Date().getTimezoneOffset() * 60 * 1000;
// parse in browser tz, not utc.
function parseAsLocalDate(text: string) {
    return new Date(Date.parse(text) + tzoffset)
}
expect(numfmt.format('mm-dd-yyyy hh:mm:ss', parseAsLocalDate('2020-10-20'))).toEqual('10-20-2020 00:00:00');
```

-----

PS. Consider updating the lib description, from "Full ECMA-376 number formatting in JavaScript" to "Full ECMA-376 number and date formatting in JavaScript".

PS2. Thanks again for this library. It works great and the code looks solid.
